name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test

  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --release --target wasm32-unknown-unknown

  wasm-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --no-typescript --target no-modules
