name: Format & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Check Rust formatting
      run: cargo fmt --all -- --check

  rust-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Check Rust linting
      run: cargo clippy --no-deps -- -D warnings -D unused-crate-dependencies
