name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: wasm-pack build
      run: wasm-pack build --no-typescript --target no-modules
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/time_tracking_manager.js
        asset_name: time_tracking_manager.js
        asset_content_type: text/javascript
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/time_tracking_manager.wasm
        asset_name: time_tracking_manager.wasm
        asset_content_type: application/wasm
